[build]
  buildCommand = "npm run build"

[services]
  [services.api]
    type = "python"
    pythonVersion = "3.11"
    buildCommand = "pip install -r scripts/requirements-zeabur.txt"
    startCommand = "python scripts/main.py"
    port = 8000
    [services.api.env]
      DEEPSEEK_API_KEY = "$DEEPSEEK_API_KEY"
      EMBEDDING_MODEL = "BAAI/bge-base-zh"
      MODEL_NAME = "deepseek-chat"
      FRONTEND_URL = "$FRONTEND_URL"
      ALLOW_ALL_ORIGINS = "true"
      PYTHONPATH = "/app"
      PYTHONUNBUFFERED = "1"
      USE_AUTH_SERVER = "true"

# 路由配置 - 所有請求都路由到 API 服務
[[routes]]
  source = "/"
  destination = "api"

[persistentVolumes]
  [persistentVolumes.storage]
    mountPath = "/app/user_documents"
    size = "1Gi"

  [persistentVolumes.indexes]
    mountPath = "/app/user_indexes"
    size = "1Gi"

  [persistentVolumes.logs]
    mountPath = "/app/logs"
    size = "500Mi"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "$NEXT_PUBLIC_API_URL" 