[build]
  buildCommand = "npm run build"

[services]
  [services.web]
    type = "nextjs"
    buildCommand = "npm run build"
    startCommand = "npm run start"
    port = 3000
    [services.web.env]
      NODE_ENV = "production"
      NEXT_PUBLIC_API_URL = "$NEXT_PUBLIC_API_URL"

  [services.api]
    type = "python"
    pythonVersion = "3.11"
    buildCommand = "pip install -r scripts/requirements-zeabur.txt"
    startCommand = "python scripts/auth_api_server.py"
    port = 8000
    [services.api.env]
      DEEPSEEK_API_KEY = "$DEEPSEEK_API_KEY"
      EMBEDDING_MODEL = "BAAI/bge-base-zh"
      MODEL_NAME = "deepseek-chat"
      FRONTEND_URL = "$FRONTEND_URL"
      ALLOW_ALL_ORIGINS = "true"

# 路由配置 - 確保 API 請求正確路由到 Python 服務
[[routes]]
  source = "/api"
  destination = "api"

[[routes]]
  source = "/auth"
  destination = "api"

[[routes]]
  source = "/health"
  destination = "api"

[[routes]]
  source = "/status"
  destination = "api"

[[routes]]
  source = "/query"
  destination = "api"

[[routes]]
  source = "/upload"
  destination = "api"

[[routes]]
  source = "/documents"
  destination = "api"

[[routes]]
  source = "/"
  destination = "web"

[persistentVolumes]
  [persistentVolumes.storage]
    mountPath = "/app/user_documents"
    size = "1Gi"

  [persistentVolumes.indexes]
    mountPath = "/app/user_indexes"
    size = "1Gi"

  [persistentVolumes.logs]
    mountPath = "/app/logs"
    size = "500Mi"

[env]
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "$NEXT_PUBLIC_API_URL" 